Added player sprites and map for level 1
I added the things that should allow the sprites to load from the .csv map file, however, on line 128 I get this error:

self.player_list.append(self.player_sprite)
TypeError: append() missing 1 required positional argument: 'item'

I don't understand why this is happening. PyCharm is telling me:
"Passing arcade.sprite.Sprite instead of arcade.sprite_list.SpriteList. Is this intentional?"
I assume that I do not want this. I will do some further research as to why this is happening.